apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - https://github.com/argoproj/rollouts-demo//examples/canary
patches:
    - path: remove-ingress-demo.yaml
    - path: remove-ingress-demo-preview.yaml
    - path: rollout-steps.yaml
images:
    - name: argoproj/rollouts-demo:blue
      newTag: red
commonAnnotations:
    version: v1.0.267
openapi:
    path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json
configurations:
    - transform.yaml
